####Simulated Data####

#Welcome the script which will produce a simulated dataset of methane labs 
#located across the USA


#Set seed for reproducibility
set.seed(4321)

#This script will produce observations of 300 fossil fuel extraction and 
#processing plants


#There will be 7 variables: longitude, latitude, company_name, fossil_fuel_type, 
#extraction_or_processing, number_of_employees, previous_leaks_n

# longitude - integer variable. Represents longitude of site. Generated from
#   random number between -124 and -66
# latitude - integer variable. Represents longitude of site. Generated from
#   random number between 27 and 48
# company_name - categorical string variable. Represents name of company running
#   site. Generated from random selection of 15 fictional company names
# fossil_fuel_type - categorical factor variable. Represents type of fossil fuel
#   used at site: either oil, coal or natural gas - randomly sampled.
# extraction_or_processing - categorical factor variable. Represents process at
#   site: either processing or extracting fuel - randomly sampled.
# number_of_employees - integer variable. Represents number of employees at
#   site. Generated by random number between 200 and 10,000
# previous_leaks_n - integer variable. Represents number of previous methane 
#   leaks at site generated by sampling random numbers from 0-20`

x <- -124.00:-66.00
longitude = sample(x, 300, replace=T)

x <- 27:48
latitude = sample(x, 300, replace=T)

x <- c("LTF", "Xeros", "Spyte", "Jeans and co", "Woodward", "Reves ltd", "Cruxx",
       "BUB Energy", "Tinted", "Leex", "Bards and Tennets", "Seets Independent",
       "Devo Minds", "Unique Oil", "COYG")
company_name = sample(x, 300, replace=T)

x <- c("Oil", "Coal", "Natural gas")
fossil_fuel_type = sample(x, 300, replace=T)

x <- c("Extraction", "Processing")
extraction_or_processing = sample(x, 300, replace=T)

x <- 200:10000
number_of_employees = sample(x, 300, replace=T)

x <- 0:20
previous_leaks_n = sample(x, 300, replace=T)

# create data.frame
df = data.frame(
  company_name, longitude, latitude, fossil_fuel_type, extraction_or_processing,
  number_of_employees, previous_leaks_n)


#Example of mapping data

library(mapview)

mapview(df, xcol = "longitude", ycol = "latitude", crs = 4269, grid = FALSE, 
          label = df$company_name, layer.name = "Fossil fuel type",
                       zcol = "fossil_fuel_type", legend=T)











